#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v25
# autospec commit: 9594167
#
Name     : R-generics
Version  : 0.1.4
Release  : 47
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/generics_0.1.4.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/generics_0.1.4.tar.gz
Summary  : Common S3 Generics not Provided by Base R Methods Related to
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
conflicts, generics provides a number of commonly used S3 generics.

%prep
%setup -q -n generics
pushd ..
cp -a generics buildavx2
popd
pushd ..
cp -a generics buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1747072389

%install
export SOURCE_DATE_EPOCH=1747072389
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/generics/DESCRIPTION
/usr/lib64/R/library/generics/INDEX
/usr/lib64/R/library/generics/LICENSE
/usr/lib64/R/library/generics/Meta/Rd.rds
/usr/lib64/R/library/generics/Meta/features.rds
/usr/lib64/R/library/generics/Meta/hsearch.rds
/usr/lib64/R/library/generics/Meta/links.rds
/usr/lib64/R/library/generics/Meta/nsInfo.rds
/usr/lib64/R/library/generics/Meta/package.rds
/usr/lib64/R/library/generics/NAMESPACE
/usr/lib64/R/library/generics/NEWS.md
/usr/lib64/R/library/generics/R/generics
/usr/lib64/R/library/generics/R/generics.rdb
/usr/lib64/R/library/generics/R/generics.rdx
/usr/lib64/R/library/generics/help/AnIndex
/usr/lib64/R/library/generics/help/aliases.rds
/usr/lib64/R/library/generics/help/generics.rdb
/usr/lib64/R/library/generics/help/generics.rdx
/usr/lib64/R/library/generics/help/paths.rds
/usr/lib64/R/library/generics/html/00Index.html
/usr/lib64/R/library/generics/html/R.css
/usr/lib64/R/library/generics/tests/testthat.R
/usr/lib64/R/library/generics/tests/testthat/_snaps/docs.md
/usr/lib64/R/library/generics/tests/testthat/test-docs.R
/usr/lib64/R/library/generics/tests/testthat/testGenericsExtension/DESCRIPTION
/usr/lib64/R/library/generics/tests/testthat/testGenericsExtension/NAMESPACE
/usr/lib64/R/library/generics/tests/testthat/testGenericsExtension/R/a.R
/usr/lib64/R/library/generics/tests/testthat/testGenericsExtension/man/reexports.Rd
/usr/lib64/R/library/generics/tests/testthat/testGenericsExtension/man/tidy-special.Rd
/usr/lib64/R/library/generics/tests/testthat/testMultiMethod/DESCRIPTION
/usr/lib64/R/library/generics/tests/testthat/testMultiMethod/NAMESPACE
/usr/lib64/R/library/generics/tests/testthat/testMultiMethod/R/a.R
/usr/lib64/R/library/generics/tests/testthat/testMultiMethod/man/multi-method-2.Rd
/usr/lib64/R/library/generics/tests/testthat/testMultiMethod/man/multi-method-3.Rd
/usr/lib64/R/library/generics/tests/testthat/testMultiMethod/man/multi-method.Rd
/usr/lib64/R/library/generics/tests/testthat/testMultiPackage/DESCRIPTION
/usr/lib64/R/library/generics/tests/testthat/testMultiPackage/NAMESPACE
/usr/lib64/R/library/generics/tests/testthat/testMultiPackage/R/a.R
/usr/lib64/R/library/generics/tests/testthat/testMultiPackage/man/multi-method-4.Rd
/usr/lib64/R/library/generics/tests/testthat/testS4Docs/DESCRIPTION
/usr/lib64/R/library/generics/tests/testthat/testS4Docs/NAMESPACE
/usr/lib64/R/library/generics/tests/testthat/testS4Docs/R/a.R
/usr/lib64/R/library/generics/tests/testthat/testS4Docs/man/multi_method.Rd
/usr/lib64/R/library/generics/tests/testthat/testSameRd/DESCRIPTION
/usr/lib64/R/library/generics/tests/testthat/testSameRd/NAMESPACE
/usr/lib64/R/library/generics/tests/testthat/testSameRd/R/a.R
/usr/lib64/R/library/generics/tests/testthat/testSameRd/man/same_rd_name-2.Rd
/usr/lib64/R/library/generics/tests/testthat/testSameRd/man/same_rd_name.Rd
/usr/lib64/R/library/generics/tests/testthat/testSingleMethod/DESCRIPTION
/usr/lib64/R/library/generics/tests/testthat/testSingleMethod/NAMESPACE
/usr/lib64/R/library/generics/tests/testthat/testSingleMethod/R/a.R
/usr/lib64/R/library/generics/tests/testthat/testSingleMethod/man/single-method-2.Rd
/usr/lib64/R/library/generics/tests/testthat/testSingleMethod/man/single-method.Rd
